### PR TITLE
Fix OSX arm64 build

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@hmaarrfk What might be the issue here? I did read https://conda-forge.org/blog/2020/10/29/macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

**Comment by hmaarrfk** [comment]
The test should be getting skipped. 

Not sure why the lines in 


https://github.com/conda-forge/staged-recipes/pull/26333/files#r1623216394

Got delet d. Add the test skip bqck

**Comment by ehfd** [comment]
OK. Thank you for pointing me to `test: native_and_emulated`. @hmaarrfk 

Btw, not only this, but the whole additional custom settings in the conda-forge.yml got deleted and went back to the default settings.

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Yeah... Adding that was optimistic

**Comment by ehfd** [comment]
@hmaarrfk Since that rocky start is now completed, we could move on to the other recipes.

This is in the order of similarity to this recipe:
https://github.com/conda-forge/staged-recipes/pull/26165 (literally same)
https://github.com/conda-forge/staged-recipes/pull/26256 (nearly same)
https://github.com/conda-forge/staged-recipes/pull/26254 (very simple)
https://github.com/conda-forge/staged-recipes/pull/26166 (X11 package, adds Windows on top of pkgw's template)
https://github.com/conda-forge/staged-recipes/pull/26242 (on Meson, modified GStreamer template - this is an X.org package yet it has no dependencies because it's a utility library that works on its own)

**Comment by hmaarrfk** [comment]
i merged those i understand, sorry i'm very rusty on windows and the whole M2 stack.

**Comment by ehfd** [comment]
@hmaarrfk Thank you!

I'll look for other people for the remaining two.

**Pull request merged**
